"use client";
import Link from "next/link";
import { motion } from "motion/react";
import VanaraLogo from "../components/VanaraLogo";
import ThemeToggle from "../components/ThemeToggle";

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1];
const GITHUB_URL = "https://github.com/vanara-ai/vanara-server";
const GITHUB_UI_URL = "https://github.com/vanara-ai/vanara-ui";

const fadeUp = {
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-surface-0 text-text-primary">
      {/* Header */}
      <header className="border-b border-border-subtle bg-surface-1/70 backdrop-blur dark:bg-surface-1/30">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
          <Link href="/">
            <VanaraLogo />
          </Link>
          <nav className="flex items-center gap-2 text-sm">
            <Link
              href="/"
              className="rounded-md px-3 py-1.5 text-text-secondary transition-colors hover:text-brand"
            >
              Home
            </Link>
            <a
              href={GITHUB_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-md px-3 py-1.5 text-text-secondary transition-colors hover:text-brand"
            >
              GitHub
            </a>
            <ThemeToggle />
          </nav>
        </div>
      </header>

      {/* Content */}
      <section className="mx-auto max-w-3xl px-4 pt-16 pb-24">
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.5, ease: EASE }}
        >
          <p className="mb-3 font-mono text-xs uppercase tracking-[0.2em] text-brand/80">
            Terms of Service
          </p>
          <h1 className="text-4xl font-semibold leading-[1.1] tracking-tight md:text-5xl">
            Use at your own risk. Good luck out there.
          </h1>
          <p className="mt-4 text-sm text-text-tertiary">
            Last updated: April 29, 2026
          </p>
        </motion.div>

        <motion.div
          {...fadeUp}
          transition={{ duration: 0.6, ease: EASE, delay: 0.1 }}
          className="mt-12 space-y-10 text-[1.0625rem] leading-relaxed text-text-secondary"
        >
          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              The short version
            </h2>
            <p>
              Vanara.ai is a free, open source, MIT-licensed tool built by
              three friends. We built it for ourselves. We think it might
              help you too. It is provided as-is with no warranty. By using
              it, you agree to the things below.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              What Vanara.ai does
            </h2>
            <p>
              It uses an LLM (hosted by Groq) to rewrite your resume against
              a job description so it matches better. You bring your own
              Groq API key. We don&apos;t charge for the service. Groq may
              charge for the API usage.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              You are responsible for what you send
            </h2>
            <p>
              Don&apos;t upload anyone else&apos;s resume without permission.
              Don&apos;t upload material you don&apos;t have rights to.
              Don&apos;t use the tool to generate content that misrepresents
              you on job applications. Recruiters can spot that, and it&apos;s
              your reputation on the line.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              LLMs make mistakes
            </h2>
            <p>
              The output is generated by an AI model. It can hallucinate,
              overstate, or say something that isn&apos;t quite true. Always
              read the output before you send it to a recruiter. You are
              responsible for the accuracy of everything on your resume. If
              a rewrite claims an experience you don&apos;t have, you are
              the one who has to catch it.
            </p>
            <p className="mt-3">
              We built in guardrails to reduce hallucinations, but they are
              not perfect. Read the final PDF end to end.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              No warranty. No guarantee.
            </h2>
            <p>
              Using Vanara.ai does not guarantee you an interview, an offer,
              or a job. The tool is provided &ldquo;as-is&rdquo; and
              &ldquo;as-available&rdquo; without any warranties of any
              kind, express or implied. That includes merchantability,
              fitness for a particular purpose, and non-infringement.
            </p>
            <p className="mt-3">
              Job searches are hard. There are a lot of factors outside our
              control. We hope it helps. We can&apos;t promise it will.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              Liability
            </h2>
            <p>
              To the maximum extent allowed by law, Vanara.ai and its
              contributors are not liable for any damages arising from
              your use of the service. This includes lost opportunities,
              lost income, or anything similar. If the tool breaks, you
              get your money back, which is nothing, because the tool is
              free.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              Your Groq API key and costs
            </h2>
            <p>
              You bring your own Groq API key. Any API costs are yours.
              Groq&apos;s free tier should comfortably cover most users;
              heavy users may hit rate limits or incur costs. Vanara.ai
              does not reimburse API costs.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              Don&apos;t abuse the service
            </h2>
            <p>
              Don&apos;t try to break it, reverse engineer our non-open bits
              (there aren&apos;t any), scrape it, or use it to attack anyone.
              If you find a bug or a security issue,{" "}
              <a
                href="mailto:vanara.ai@yahoo.com"
                className="text-text-primary underline underline-offset-4 hover:text-brand"
              >
                email us
              </a>{" "}
              before disclosing publicly, please.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              We can change or shut this down
            </h2>
            <p>
              Vanara.ai is a side project by three people with full-time
              jobs. We may update the service, break something, or take it
              offline. The source code is open under MIT — if we ever go
              away, you can fork it, self-host it, or keep it running
              yourself. That&apos;s the whole point of the license.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              The code is open source
            </h2>
            <p>
              Everything is MIT licensed:{" "}
              <a
                href={GITHUB_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="text-text-primary underline underline-offset-4 hover:text-brand"
              >
                backend
              </a>{" "}
              ·{" "}
              <a
                href={GITHUB_UI_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="text-text-primary underline underline-offset-4 hover:text-brand"
              >
                frontend
              </a>
              . Fork it, run it yourself, build on it. If you find a bug or
              want a feature, open an issue or a pull request.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              Changes to these terms
            </h2>
            <p>
              If we change the terms, we&apos;ll update the date at the top
              and the change will show up in the commit history of this
              page. Continued use after a change means you accept the new
              terms.
            </p>
          </div>

          <div>
            <h2 className="mb-3 text-xl font-semibold text-text-primary">
              Contact
            </h2>
            <p>
              Email{" "}
              <a
                href="mailto:vanara.ai@yahoo.com"
                className="text-text-primary underline underline-offset-4 hover:text-brand"
              >
                vanara.ai@yahoo.com
              </a>{" "}
              with any questions.
            </p>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border-subtle bg-surface-1 py-8 dark:bg-surface-0">
        <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 text-sm text-text-tertiary">
          <div>
            © {new Date().getFullYear()} Vanara.ai · MIT Licensed ·{" "}
            <a
              href={GITHUB_URL}
              className="underline underline-offset-4 hover:text-text-primary"
              target="_blank"
              rel="noopener noreferrer"
            >
              Source
            </a>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="hover:text-text-primary">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-text-primary">
              Terms
            </Link>
            <a
              href="mailto:vanara.ai@yahoo.com"
              className="hover:text-text-primary"
            >
              Contact
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}